name: momeet
description: "Plan your day efficiently with an directly calendar and todo list."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1

  # Lifecycle
  riverpod: ^3.1.0
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

  # HTTP Client
  dio: ^5.9.1
  retrofit: ^4.9.2
  # momeet_api:
  #   path: lib/shared/api/generated/

  # Build Pacakge
  built_collection: ^5.1.1
  built_value: ^8.12.3

  # Routing
  go_router: ^17.0.1

  # Local Preferences
  shared_preferences: ^2.5.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Authorization
  supabase: ^2.10.2
  supabase_flutter: ^2.12.0

  # UI utilities
  flutter_animate: ^4.5.2
  intl: ^0.20.2

  # Calendar
  syncfusion_flutter_calendar: ^32.1.25

  # Annotation
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.11.0

  # Code Generator (Rivorpod)
  riverpod_generator: ^4.0.0

  # Code Generator (Open API)
  # openapi_generator_cli: ^6.1.0
  retrofit_generator: ^10.2.1
  swagger_parser: ^1.42.0
  json_serializable: ^6.9.0

  # Freezed
  freezed: ^3.2.3

  # Testing
  mocktail: ^1.0.4

  # Architecture Lints
  custom_lint:
  momeet_lints:
    path: packages/momeet_lints


flutter:
  uses-material-design: true

  assets:
    - assets/.env

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
