name: momeet
description: "Plan your day efficiently with an directly calendar and todo list."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Lifecycle
  riverpod: ^3.1.0
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

  # HTTP Client
  dio: ^5.9.1

  # Routing
  go_router: ^17.0.1

  # Local Preferences
  shared_preferences: ^2.5.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Authorization
  supabase_flutter: ^2.12.0

  # UI utilities
  flutter_animate: ^4.5.2
  intl: ^0.20.2

  # Calendar
  syncfusion_flutter_calendar: ^32.1.25

  # Freezed Model
  freezed: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code Generator (Rivorpod)
  build_runner: ^2.10.5
  riverpod_generator: ^4.0.0

  # Code Generator (Open API)
  openapi_generator_cli: ^6.1.0

  # Freezed Model
  freezed_annotation: ^3.1.0

  # Testing
  mocktail: ^1.0.4


flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
